// <auto-generated />
using System;
using EI.API.ProcessLogging.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EI.API.ProcessLogging.Data.Migrations
{
    [DbContext(typeof(ProcessLogDbContext))]
    [Migration("20250918010720_AddActivityType_PayorContractAnalysis")]
    partial class AddActivityType_PayorContractAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ActivityTypeId");

                    b.Property<bool>("IsInbound")
                        .HasColumnType("bit")
                        .HasColumnName("Inbound");

                    b.Property<bool>("IsOutbound")
                        .HasColumnType("bit")
                        .HasColumnName("Outbound");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ActivityType");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ActivityTypesHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("27a1378d-e392-486e-a63f-8c2414e44c1d"),
                            IsInbound = true,
                            IsOutbound = false,
                            RowVersion = new byte[0],
                            Type = "ReceiveFile",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("702524f1-6ae1-4989-8480-1a00b0bbc04d"),
                            IsInbound = true,
                            IsOutbound = false,
                            RowVersion = new byte[0],
                            Type = "PayorContractAnalysis",
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ActivityTypeTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ActivityTypeId");

                    b.Property<string>("CultureCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id", "CultureCode");

                    b.ToTable("ActivityTypeTranslations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ActivityTypeTranslationsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("27a1378d-e392-486e-a63f-8c2414e44c1d"),
                            CultureCode = "en-US",
                            Description = "File received from external system",
                            Name = "Receive File",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("702524f1-6ae1-4989-8480-1a00b0bbc04d"),
                            CultureCode = "en-US",
                            Description = "Payor Contract Analysis from external system",
                            Name = "Payor Contract Analysis",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.FileProcessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FileProcessLogId");

                    b.Property<string>("FileHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("FileSize")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("ProcessLogId");

                    b.ToTable("FileProcessLogs", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("FileProcessLogsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.MessageLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageLevelId");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MessageLevel");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.ToTable("MessageLevels", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("MessageLevelsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e8d0b7e-811a-47f3-bb5a-b64eb9fb92c8"),
                            Level = "Information",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("198aa513-a2a2-4781-9e19-d79af8947cdd"),
                            Level = "Status",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("36304564-2b06-401d-b71f-b9062890edb9"),
                            Level = "Warning",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("ee72bde9-e89d-4bc0-b91b-9294f160fbf9"),
                            Level = "Error",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("7252f49d-ca4c-4623-be6d-55c90602c1c1"),
                            Level = "Fatal",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.MessageLevelTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageLevelId");

                    b.Property<string>("CultureCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id", "CultureCode");

                    b.ToTable("MessageLevelTranslations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("MessageLevelTranslationsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e8d0b7e-811a-47f3-bb5a-b64eb9fb92c8"),
                            CultureCode = "en-US",
                            Description = "Message is a routine status message",
                            Name = "Informational",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("198aa513-a2a2-4781-9e19-d79af8947cdd"),
                            CultureCode = "en-US",
                            Description = "Record of the Event Log entry's status changing",
                            Name = "Status Change",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("36304564-2b06-401d-b71f-b9062890edb9"),
                            CultureCode = "en-US",
                            Description = "A message describing a potentially problematic issue while processing the Event",
                            Name = "Warning",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("ee72bde9-e89d-4bc0-b91b-9294f160fbf9"),
                            CultureCode = "en-US",
                            Description = "A message describing an error that occurred while processing the Event",
                            Name = "Error",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("7252f49d-ca4c-4623-be6d-55c90602c1c1"),
                            CultureCode = "en-US",
                            Description = "A message describing a severe error that halted processing of the Event",
                            Name = "Fatal",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcessLogId");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProcessStatus");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ActivityType");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("ProcessLogs", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProcessLogsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessLogMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcessLogMessageId");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MessageLevel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProcessLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("ProcessLogId");

                    b.ToTable("ProcessLogMessages", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProcessLogMessagesHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcessStatusId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProcessStatus");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.ToTable("ProcessStatuses", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProcessStatusesHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ed43de1-a88d-4e53-8370-51738497c0da"),
                            RowVersion = new byte[0],
                            Status = "New",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("6dfe6ee6-36d8-428f-97b2-571def4a6fb4"),
                            RowVersion = new byte[0],
                            Status = "InProgress",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("8ed812bd-1761-4d34-ad12-f4d9515ff43e"),
                            RowVersion = new byte[0],
                            Status = "Paused",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("efd534e1-db63-4b03-a36e-523fa9c14963"),
                            RowVersion = new byte[0],
                            Status = "Completed",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("c59f50b2-d7c2-4a6f-897c-5b9ec0d3d539"),
                            RowVersion = new byte[0],
                            Status = "Failed",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("d40d80f7-eb09-4f95-86fa-79ff569e7907"),
                            RowVersion = new byte[0],
                            Status = "Cancelled",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("d7c7ae65-285e-47a4-b421-5bdc9b39aec2"),
                            RowVersion = new byte[0],
                            Status = "Duplicate",
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessStatusTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcessStatusId");

                    b.Property<string>("CultureCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id", "CultureCode");

                    b.ToTable("ProcessStatusTranslations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProcessStatusTranslationsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ed43de1-a88d-4e53-8370-51738497c0da"),
                            CultureCode = "en-US",
                            Description = "Event has been received but not yet started",
                            Name = "New",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("6dfe6ee6-36d8-428f-97b2-571def4a6fb4"),
                            CultureCode = "en-US",
                            Description = "Event is currently in-progress",
                            Name = "In-Progress",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("8ed812bd-1761-4d34-ad12-f4d9515ff43e"),
                            CultureCode = "en-US",
                            Description = "Event processing was started, but is currently on hold with no activity occurring",
                            Name = "Paused",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("efd534e1-db63-4b03-a36e-523fa9c14963"),
                            CultureCode = "en-US",
                            Description = "Event processing completed successfully",
                            Name = "Complete",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("c59f50b2-d7c2-4a6f-897c-5b9ec0d3d539"),
                            CultureCode = "en-US",
                            Description = "Event processing completed unsuccessfully",
                            Name = "Failed",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("d40d80f7-eb09-4f95-86fa-79ff569e7907"),
                            CultureCode = "en-US",
                            Description = "Event processing was started, but ended without completing",
                            Name = "Cancelled",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("d7c7ae65-285e-47a4-b421-5bdc9b39aec2"),
                            CultureCode = "en-US",
                            Description = "Event processing was halted after being identified as a duplicate of an earlier, un-cancelled process",
                            Name = "Duplicate",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12FunctionalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("X12FunctionalGroupId");

                    b.Property<string>("ApplicationReceiverCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ApplicationSenderCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Date")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FunctionalIdentifierCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("GroupControlNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ResponsibleAgencyCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("X12Status");

                    b.Property<string>("Time")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.Property<string>("VersionReleaseIndustryIdentifierCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("X12InterchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("X12InterchangeId");

                    b.ToTable("X12FunctionalGroups", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("X12FunctionalGroupsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12Interchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("X12InterchangeId");

                    b.Property<string>("AcknowledgementRequested")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ComponentElementSeparator")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<Guid>("FileProcessLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InterchangeControlNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("InterchangeControlVersionNumber")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("InterchangeDate")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("InterchangeReceiverId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("InterchangeReceiverIdQualifier")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InterchangeSenderId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("InterchangeSenderIdQualifier")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InterchangeTime")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("RepetitionSeparator")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("X12Status");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UsageIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("FileProcessLogId");

                    b.HasIndex("Status");

                    b.ToTable("X12Interchanges", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("X12InterchangesHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("X12MessageId");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MessageLevel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.Property<Guid?>("X12FunctionalGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("X12InterchangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("X12TransactionSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("X12FunctionalGroupId");

                    b.HasIndex("X12InterchangeId");

                    b.HasIndex("X12TransactionSetId");

                    b.ToTable("X12Messages", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("X12MessagesHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("X12StatusId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("X12Status");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.ToTable("X12Statuses", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("X12StatusesHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("21c50e68-788d-41c5-a4f1-05d1e9aa00f8"),
                            RowVersion = new byte[0],
                            Status = "Accepted",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("cf1e5c7f-c9b7-443f-b7fb-bdac96c9fc60"),
                            RowVersion = new byte[0],
                            Status = "Rejected",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("e119c843-1c46-4571-b379-eee66f6b7e7b"),
                            RowVersion = new byte[0],
                            Status = "Invalid",
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("65a9f7ab-757f-4fc8-bbce-571039900b9e"),
                            RowVersion = new byte[0],
                            Status = "Duplicate",
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12StatusTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("X12StatusId");

                    b.Property<string>("CultureCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id", "CultureCode");

                    b.ToTable("X12StatusTranslations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("X12StatusTranslationsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));

                    b.HasData(
                        new
                        {
                            Id = new Guid("21c50e68-788d-41c5-a4f1-05d1e9aa00f8"),
                            CultureCode = "en-US",
                            Description = "The X12 record was validated and accepted",
                            Name = "Accepted",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("cf1e5c7f-c9b7-443f-b7fb-bdac96c9fc60"),
                            CultureCode = "en-US",
                            Description = "The X12 record was rejected for reasons other than being Invalid",
                            Name = "Rejected",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("e119c843-1c46-4571-b379-eee66f6b7e7b"),
                            CultureCode = "en-US",
                            Description = "The X12 record was rejected do to validation errors",
                            Name = "Error",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        },
                        new
                        {
                            Id = new Guid("65a9f7ab-757f-4fc8-bbce-571039900b9e"),
                            CultureCode = "en-US",
                            Description = "The X12 record was rejected as a duplicate",
                            Name = "Duplicate",
                            RowVersion = new byte[0],
                            UpdatedBy = "Reference Data 1.0"
                        });
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12TransactionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("X12TransactionSetId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("X12Status");

                    b.Property<string>("TransactionSetControlNumber")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("TransactionSetIdentifierCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTo");

                    b.Property<Guid>("X12FunctionalGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("X12FunctionalGroupId");

                    b.ToTable("X12TransactionSets", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("X12TransactionSetsHistory");
                                ttb
                                    .HasPeriodStart("ValidFrom")
                                    .HasColumnName("ValidFrom");
                                ttb
                                    .HasPeriodEnd("ValidTo")
                                    .HasColumnName("ValidTo");
                            }));
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ActivityTypeTranslation", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.ActivityType", "Entity")
                        .WithMany("Translations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.FileProcessLog", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.ProcessLog", "ProcessLog")
                        .WithMany()
                        .HasForeignKey("ProcessLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessLog");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.MessageLevelTranslation", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.MessageLevel", "Entity")
                        .WithMany("Translations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessLog", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.ProcessStatus", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .HasPrincipalKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.ActivityType", null)
                        .WithMany()
                        .HasForeignKey("Type")
                        .HasPrincipalKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessLogMessage", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.MessageLevel", null)
                        .WithMany()
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.ProcessLog", "ProcessLog")
                        .WithMany()
                        .HasForeignKey("ProcessLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessLog");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessStatusTranslation", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.ProcessStatus", "Entity")
                        .WithMany("Translations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12FunctionalGroup", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12Status", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .HasPrincipalKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12Interchange", "X12Interchange")
                        .WithMany()
                        .HasForeignKey("X12InterchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("X12Interchange");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12Interchange", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.FileProcessLog", "FileProcessLog")
                        .WithMany()
                        .HasForeignKey("FileProcessLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12Status", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .HasPrincipalKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileProcessLog");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12Message", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.MessageLevel", null)
                        .WithMany()
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12FunctionalGroup", "X12FunctionalGroup")
                        .WithMany()
                        .HasForeignKey("X12FunctionalGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12Interchange", "X12Interchange")
                        .WithMany()
                        .HasForeignKey("X12InterchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12TransactionSet", "X12TransactionSet")
                        .WithMany()
                        .HasForeignKey("X12TransactionSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("X12FunctionalGroup");

                    b.Navigation("X12Interchange");

                    b.Navigation("X12TransactionSet");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12StatusTranslation", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12Status", "Entity")
                        .WithMany("Translations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12TransactionSet", b =>
                {
                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12Status", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .HasPrincipalKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EI.API.ProcessLogging.Data.Entities.X12FunctionalGroup", "X12FunctionalGroup")
                        .WithMany()
                        .HasForeignKey("X12FunctionalGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("X12FunctionalGroup");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ActivityType", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.MessageLevel", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.ProcessStatus", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("EI.API.ProcessLogging.Data.Entities.X12Status", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
